site_name: Docs | Cannlytics
site_url: https://cannlytics.com/docs
repo_url: https://github.com/cannlytics/cannlytics-console
# edit_uri: tree/master/docs/src/cannlytics
edit_uri: ""
site_description: Simple and easy cannabis analytics.
copyright: |
  Copyright &copy; 2021 <a href="https://github.com/cannlytics"  target="_blank" rel="noopener">Cannlytics</a>

docs_dir: docs/markdown
theme:
  name: material
  custom_dir: docs/theme
  favicon: assets/images/favicon.ico
  logo: assets/images/cannlytics_calyx_512.svg
  palette:
    - scheme: default
      primary: teal
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Lora
    code: Roboto Mono
  features:
    - navigation.tabs

nav:
  - Home:
    - Installation: installation.md
  - FAQ:
    - Frequently Asked Questions: faq.md
  - About:
    - Contributing &amp; Support: about/contributing.md
    - Development: about/development.md
    - Changelog: about/changelog.md
    - Release Notes:
        - '0.0.3': about/releases/0.0.3.md
  - License: about/license.md

markdown_extensions:
  - markdown.extensions.toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: ""
  - markdown.extensions.admonition:
  - markdown.extensions.smarty:
      smart_quotes: false
  - pymdownx.betterem:
  - markdown.extensions.attr_list:
  - markdown.extensions.def_list:
  - markdown.extensions.tables:
  - markdown.extensions.abbr:
  - markdown.extensions.footnotes:
  - markdown.extensions.md_in_html:
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
        # - name: md-render
        #   class: md-render
        #   format: !!python/name:docs.tools.pymdownx_md_render.md_sub_render
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
        - name: pycon3
          lang: pycon
          options:
            python3: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite:
      custom_inline:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.inline_mathjax_format
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      user: cannlytics
      repo: cannlytics-engine
      # normalize_issue_symbols: true
  - pymdownx.tilde:
  - pymdownx.caret:
  - pymdownx.smartsymbols:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar:
  - pymdownx.arithmatex:
  - pymdownx.mark:
  - pymdownx.striphtml:
  # - pymdownx.snippets:
  #     base_path: docs/src/markdown/_snippets
  - pymdownx.keys:
      separator: "\uff0b"
  - pymdownx.details:
  - pymdownx.tabbed:
  - pymdownx.saneheaders:

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/cannlytics
extra_css:
  - assets/pymdownx-extras/extra-75bc45e106.css
extra_javascript:
  - assets/pymdownx-extras/extra-uml-51b11a9a.js

plugins:
  - search
  # - git-revision-date-localized
  # - git-revision-date
  - minify:
      minify_html: true