openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api:
    get:
      operationId: listindexs
      description: Informational base endpoint.
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - api
  /api{format}:
    get:
      operationId: retrieveindex
      description: Informational base endpoint.
      parameters:
      - name: format
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api{format}
  /api/labs/:
    get:
      operationId: listlabs
      description: Get or update information about labs.
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - api
    post:
      operationId: createlabs
      description: Get or update information about labs.
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/labs/{format}:
    get:
      operationId: retrievelabs
      description: Get or update information about labs.
      parameters:
      - name: format
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
    post:
      operationId: createlabs
      description: Get or update information about labs.
      parameters:
      - name: format
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/labs/{org_id}/:
    get:
      operationId: retrievelab
      description: Get or update information about a lab.
      parameters:
      - name: org_id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/labs/{org_id}{format}:
    get:
      operationId: retrievelab
      description: Get or update information about a lab.
      parameters:
      - name: org_id
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: format
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/labs/{org_id}/analyses/:
    get:
      operationId: listlab_analyses
      description: Get or update (TODO) lab analyses.
      parameters:
      - name: org_id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - api
    post:
      operationId: createlab_analyses
      description: Get or update (TODO) lab analyses.
      parameters:
      - name: org_id
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/labs/{org_id}/analyses{format}:
    get:
      operationId: retrievelab_analyses
      description: Get or update (TODO) lab analyses.
      parameters:
      - name: org_id
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: format
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
    post:
      operationId: createlab_analyses
      description: Get or update (TODO) lab analyses.
      parameters:
      - name: org_id
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: format
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/labs/{org_id}/logs/:
    get:
      operationId: listlab_logs
      description: Get or create lab logs.
      parameters:
      - name: org_id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - api
    post:
      operationId: createlab_logs
      description: Get or create lab logs.
      parameters:
      - name: org_id
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/labs/{org_id}/logs{format}:
    get:
      operationId: retrievelab_logs
      description: Get or create lab logs.
      parameters:
      - name: org_id
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: format
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
    post:
      operationId: createlab_logs
      description: Get or create lab logs.
      parameters:
      - name: org_id
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: format
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /apiusers/:
    get:
      operationId: listusers
      description: Get, update, or create user's data.
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - apiusers
    post:
      operationId: createusers
      description: Get, update, or create user's data.
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - apiusers
  /apiusers/{format}:
    get:
      operationId: retrieveusers
      description: Get, update, or create user's data.
      parameters:
      - name: format
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - apiusers
    post:
      operationId: createusers
      description: Get, update, or create user's data.
      parameters:
      - name: format
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - apiusers
  /apiusers/{uid}/:
    get:
      operationId: retrieveusers
      description: Get, update, or create user's data.
      parameters:
      - name: uid
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - apiusers
    post:
      operationId: createusers
      description: Get, update, or create user's data.
      parameters:
      - name: uid
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - apiusers
  /apiusers/{uid}{format}:
    get:
      operationId: retrieveusers
      description: Get, update, or create user's data.
      parameters:
      - name: uid
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: format
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - apiusers
    post:
      operationId: createusers
      description: Get, update, or create user's data.
      parameters:
      - name: uid
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: format
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - apiusers
